### ISSUE TITLE
Constants are not exposed

### ISSUE THREAD

**Issue by Simon-Laux** [deltachat-bot/deltachat-node-bot-base#2] opened 2020-02-24 20:29 UTC
Solution:
re-Export the `C` object from dc-node

**Comment by pabzm** [comment] 2020-02-25 12:52
The C constants are absent by design. In my eyes, a library should encapsulate such low level details. I'd like to enable people to write bots without reading `deltachat.h`.

#3 can be solved differently (see over there), so I see no imminent need to expose the constants, thus I'm closing this.

**Closed as completed by pabzm** 2020-02-25 12:52 UTC
Labels: bug
